export const data = [
  {
    "id":1,
    "title": "Karl",
    "shortDesc": "Developer",
    "longDesc": "DeveloperDeveloperDeveloperDeveloperDeveloper",
    "startDate": new Date('October 10, 2022').getDate(),
    "endDate": new Date('Novemver 1, 2022').getDate(),
    "placeStart": "Moscow",
    "placeEnd": "Kazan",
    "image": "1.jpg",
    "activity": 'Женское',
    "likedUsers": [],
    "dislikedUsers": [],
    "likedBy": [],
    "price": 10000,
    "organizator": {organizatorName:'Jora',organizatorAva: '3.jpg', organizatorRating: 4.2},
    "participant": [{participantName: 'Igor', participantAva:'1.jpg'}, {participantName:'Katya', participantAva:'2.jpg'}]
  },
  {
    "id": 1,
    "name": "Martin",
    "desc": "Prisoner at Federal Correctional Institution",
    "age": 35,
    "image": "2.jpg",
    "likedUsers": [],
    "superLikedUsers": [],
    "dislikedUsers": [],
    "likedBy": [],
    "price": 20000
  },
  {
    "id": 2,
    "name": "Emily",
    "desc": "Actress",
    "age": 35,
    "image": "3.jpg",
    "likedUsers": [],
    "superLikedUsers": [],
    "dislikedUsers": [],
    "likedBy": [],
    "price": 30000
  },
  {
    "id": 3,
    "name": "Michael",
    "desc": "Manager",
    "age": 45,
    "image": "4.jpg",
    "likedUsers": [],
    "superLikedUsers": [],
    "dislikedUsers": [],
    "likedBy": [],
    "price": 40000
  },
  {
    "id": 4,
    "name": "Dwight",
    "desc": "Sales",
    "age": 40,
    "image": "5.jpg",
    "likedUsers": [],
    "superLikedUsers": [],
    "dislikedUsers": [],
    "likedBy": [],
    "price": 50000
  },
  {
    "id": 5,
    "name": "Jessica",
    "desc": "Actress",
    "age": 37,
    "image": "6.jpg",
    "likedUsers": [],
    "superLikedUsers": [],
    "dislikedUsers": [],
    "likedBy": [],
    "price": 60000
  },
  {
    "id": 6,
    "name": "Alexandra",
    "desc": "Actress",
    "age": 32,
    "image": "7.jpg",
    "likedUsers": [],
    "superLikedUsers": [],
    "dislikedUsers": [],
    "likedBy": [],
    "price": 70000
  }
]
